/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_SongLED1_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SongLED1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SongLED1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SongLED1_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                           /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_SongLED2_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SongLED2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SongLED2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SongLED2_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                           /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_SongLED3_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_SongLED3_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SongLED3_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SongLED3_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                           /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_TrackLED1_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_TrackLED1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_TrackLED1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_TrackLED1_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                            /* @} */

/*! @name PORTE29 (number 21), J10[9]
  @{ */
#define BOARD_INITPINS_TrackLED2_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_TrackLED2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_TrackLED2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_TrackLED2_PIN 29U    /*!<@brief PORTE pin index: 29 */
                                            /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */
#define BOARD_INITPINS_VolumeLED_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_VolumeLED_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_VolumeLED_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_VolumeLED_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                            /* @} */

/*! @name PORTC1 (number 56), J10[12]/U6[31]/A5
  @{ */
#define BOARD_INITPINS_VolumeInput_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_VolumeInput_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                              /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_VolumeOutput_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_VolumeOutput_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                               /* @} */

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */
#define BOARD_INITPINS_Prev_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Prev_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Prev_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Prev_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                       /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_Next_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Next_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Next_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Next_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                       /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_Play_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Play_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Play_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Play_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
